### ISSUE TITLE
Phone book - icons

### ISSUE THREAD

**Issue by HexTree** [HexTree/orientation-app#21]
Design icons for the phone contacts (e.g. the taxi company can have a taxi for the icon). I think we should go for at least 140x140 pixels for each icon.

**Comment by HexTree** [comment]
Need to wait for #40 to be complete before doing this.

**Comment by HexTree** [comment]
Ok, content is filled.

**Comment by hadjimy** [comment]
Icons are added (#51) and are located in drawable/contacts folder.
Main menu icons have a scaled resolution in the drawable-dpi folders.
Do we need to adjust the resolution for the contact icons too?
