### ISSUE TITLE
Main menu - icons for buttons

### ISSUE THREAD

**Issue by HexTree** [HexTree/orientation-app#22]
Design icons for the buttons on the main menu.

**Comment by HexTree** [comment]
Icons uploaded in 7e4604d175df36dc18d52a09e731d444327582c3

**Comment by Uchman21** [comment]
Icons added. Need the App logo and contact/person logo still though

**Comment by yipcma** [comment]
could use this? http://fortawesome.github.io/Font-Awesome/icons/

**Comment by hadjimy** [comment]
Revised the icons. 
For personal contacts we can use the relevant profile photo (if corresponding person agrees with that). For the rest (taxi, GA services etc) I can create the icons.

**Comment by HexTree** [comment]
Need an icon for Travel. A taxi symbol doesn't quite fit the purpose. Could do a bus, but I think something like a landscape and a palm tree might be more aesthetic.

**Comment by yipcma** [comment]
this could be helpful
http://www.flaticon.com/

**Comment by HexTree** [comment]
da613efc6d4289846dacb2183ec7119dac474426 There is a bus icon to use for travel. @Uchman21 could you replace the taxi/plane icons with the bus in the correct folders? I'm not sure exactly the right way to do this.
