### ISSUE TITLE
Calendar - grid sizing bug

### ISSUE THREAD

**Issue by HexTree** [HexTree/orientation-app#26]
I get a sizing problem with the week grid on my Galaxy Mini S5570. Need to fix the layout so that the user doesn't need to scroll to see the day numbers.

![p1010925](https://cloud.githubusercontent.com/assets/7933725/8508039/59b11500-2268-11e5-98c5-54e944f7228f.JPG)

**Comment by Uchman21** [comment]
Check it again. Now Its using CalendarView
