### ISSUE TITLE
Bus trip planner integration

### ISSUE THREAD

**Issue by yipcma** [HexTree/orientation-app#29]
I've been maintaining a real-time geo-tagged bus trip planner for the colored and jeddah routes at [KBus](http://kbus.info) which I've made responsive. You guys are most welcomed to integrate it to the orientation-app. KBus is currently at alpha and will have some new functionalities such as route visualization, and an updated post-Ramadan schedule of course. Lemme know if you have any questions.

**Comment by HexTree** [comment]
Yes we will try to put this in. At minimum, as a web link in the Travel section. It would be nice to make it a native app, but we may not have the time for it.

**Comment by yipcma** [comment]
web-link would suffice for now. I'm working on making it more responsive on hand-held devices.

use http://kbus.info

**Comment by HexTree** [comment]
20b3dff4a60e6e129fbcdbc7a2011c3f90fb6a9b bus planner is now in a webview in the Travel section. The site looks good on my phone.

**Comment by yipcma** [comment]
thanks buddy, i will update the site tonight when i get back to the hotel.
