### ISSUE TITLE
Main menu - alphabetical order

### ISSUE THREAD

**Issue by HexTree** [HexTree/orientation-app#36]
We want the main menu icons to be in alphabetical order. From first glance at the code it wasn't clear to me why 'About' is appearing last, instead of first.

**Comment by Uchman21** [comment]
The icons were arranged in order of importance.

**Comment by HexTree** [comment]
Ah, ok. I think it is best to have 'About' first, because that will contain the message 'Welcome to KAUST' and a brief description of the other menu items. It should be the first thing they click on. In that case, alphabetical order will be most suitable.

**Comment by Uchman21** [comment]
Ok.. I will move about up.. Just didn't know what the about was for.
Thought it was about the app

**Comment by HexTree** [comment]
f4305ff516ee4ecb1d67b0348fac4a9177ac7216
