### ISSUE TITLE
Main menu - background

### ISSUE THREAD

**Issue by HexTree** [HexTree/orientation-app#37]
Background image or design for the main menu.

**Comment by HexTree** [comment]
fe72316f54a66d7ed035b20e0bdffb1ebdfba8d7 With this new change the background is on all menus, not just the main one. I'm not too sure about this, it looks strange on things like calendar, and for scrollable menus like Contacts it interferes with the text. The scrollable items should really be kept clear for maximum readability. I would suggest to keep the background for only Main Menu. Maybe we can have a plain colour for the others. What do you think @Uchman21 @hadjimy 

![contacts back](https://cloud.githubusercontent.com/assets/7933725/9150515/54774ce2-3de5-11e5-87da-7e021e9ef9e4.png)

**Comment by hadjimy** [comment]
The background was meant to replace only the main menu pattern. I won't use it for the rest of the pages. As Liam said it is hard to make it compatible with the various text in other menus. Besides I tried to make the difference between the background and previously used pattern small. If you think is better to make the background more neutral let me know to change it.

**Comment by Uchman21** [comment]
The background looks ok for me. Maybe for the calendar it might look a bit off. I really don't see how it interferes with the scrollables. But i wouldn't go for a plane background. but for the same background but brighter. Like a bit whiter. A plane background is  not good for an app. I would suggest a whiter background. same design like the one on home but whiter/brighter .

**Comment by HexTree** [comment]
The issue is not with the background, but with the items themselves being transparent. It looks ok when stationary, but when you scroll up and down I really don't think it works. The many lines and angles of the beacon do not complement well with the text. Our brain has to do more work distinguishing the two. I think it must be some rule of aesthetics for the space behind text to always be very smooth. If we could come up with a background which is smoother and less angular, then maybe that would work ok. Because then you can actually 'see' it behind the text.

Also note that for Checklist and Web Links, the scrollable items are supposed to be clickable. They do not have a 'clickable' feel if they are transparent. Clickable things normally have volume and/or opacity to indicate such.

I would suggest the best approach right now is leave the pattern without the beacon for all menus except main menu. And in the meantime we could ask someone like the graphic designer working on the Orientation Posters, to see what their opinion is.

**Comment by hadjimy** [comment]
I will try to experiment with a brighter background to see if this looks
better. Otherwise we can just keep the background image only for the main
menu.

**Comment by HexTree** [comment]
Yes, I think it looks much better with the current level of brightness. I do not feel there is any interference now. I think for the calendar (not the top level, but the day schedule layout) we should get rid of the beacon or make it brighter, it doesn't look good to only see the very tip of the beacon and have the rest obscured by the menu.

**Comment by hadjimy** [comment]
Ok, use any of the background files you think is the best. All contact icons (according to my list) are already uploaded so we only need to change the relevant entries in the files.
I won't be able to do anything more for the app tomorrow at least until late in the night.

**Comment by Uchman21** [comment]
I have already taken care of all those.Check the latest version

**Comment by HexTree** [comment]
I'll stick to using background15 in the places which need brightness. So the rest can be deleted.
