### ISSUE TITLE
Main menu - size issue for small screens

### ISSUE THREAD

**Issue by HexTree** [HexTree/orientation-app#38]
One of the icons is sized strangely on the emulator for a small screen.

![small screen](https://cloud.githubusercontent.com/assets/7933725/9110006/d4670766-3c42-11e5-96d9-bef47aa0c4e7.png)

**Comment by hadjimy** [comment]
This might be because the icons do not have exactly the same dimensions. I will have a look if there is an easy fix to this, by making uniform dimensions and without stretching much the icons.

**Comment by Uchman21** [comment]
fixed. No need to change the dimension

**Comment by HexTree** [comment]
Yes, for safety the app should be designed such that the layout is correct regardless of the differences in icon dimensions.

**Comment by HexTree** [comment]
Best not to close any issues until the fix is merged into Master.

**Comment by Uchman21** [comment]
Done

**Comment by Uchman21** [comment]
The phone contact picture still remains like that till i get the real icons that are gonna be used

**Comment by HexTree** [comment]
Great, the issue on my phone was fixed as well.
