### ISSUE TITLE
Calendar - Content

### ISSUE THREAD

**Issue by HexTree** [HexTree/orientation-app#39]
Fill calendar with content

**Comment by HexTree** [comment]
dd313d9109af37a5b9b203922dd4cf7b7eeb9235 The second week is complete. For the first week, I have added all events up to and including Group Light Lunch at 12:30pm. I'm releasing the lock on this task now and will take it up again when I get the chance. If anyone wants to add content, please assign this task to yourself first, and release assignment when done.

**Comment by Uchman21** [comment]
Completed from 9th to the 13th. Anyone can continue with completing 14th and 15th which are the only remaining ones. I will release this and if i find time again, then i will take it up.

**Comment by HexTree** [comment]
a59e7af58ffd59b689cae28837859a44bf98d6c3 Done
