### ISSUE TITLE
About - 'back' button doesn't work

### ISSUE THREAD

**Issue by HexTree** [HexTree/orientation-app#42]
Weird issue on my phone (Galaxy Mini S5570). In the About menu, clicking the 'back' button on the title bar doesn't do anything. I have to use the phone buttons to go back.

Have not observed this in the emulator, or in any other menu, so maybe it is specific to my phone. If this bug is not observed anywhere else then we can disregard it as an anomaly.

**Comment by Uchman21** [comment]
Works on mine

**Comment by HexTree** [comment]
Closing due to non-reproducibility.
