### ISSUE TITLE
Google play upload.

### ISSUE THREAD

**Issue by Uchman21** [HexTree/orientation-app#45]
When are we gonna upload the app. I think the earlier the better. we can make changes while its there. Or are we waiting for it to get approved ?

**Comment by hadjimy** [comment]
Make some changes in icons. See #46.
If everything looks good we can upload to google play.

**Comment by HexTree** [comment]
We are waiting for approval, hopefully Sunday morning but I don't know for sure. However I can probably just upload it and keep it not visible to the public. I'll look into this when I get to the office.

**Comment by HexTree** [comment]
I'll upload within the next hour.

**Comment by HexTree** [comment]
Published just now. Pending approval from Google.
