### ISSUE TITLE
Travel

### ISSUE THREAD

**Issue by HexTree** [HexTree/orientation-app#5]
- Maps of the area, including KAUST, Thuwal, Jeddah and possibly beyond. The idea here was to create something based on Open Street Maps, and to use the remarkably detailed overlays provided at https://github.com/Virtakuono/.kml-repository . The maps can also be supplemented with travel information. This would be a great help to the newcomers, because even some of us who have been here several years still don't know much about what's beyond the walls.

Update: It was suggested to include a http://maps.me/en/home package for this.

**Comment by HexTree** [comment]
A lot of useful data in the various repositories at https://github.com/Virtakuono . This task will need more thought for design than the others.

**Comment by Virtakuono** [comment]
Check out this https://github.com/mapswithme/api-ios and  the base maps come from OSM, through maps.me, you can open up locations within maps.me from outside the app using this API. https://github.com/mapswithme/api-android. As far as the actual data is concerned, just tell me what you need, I think most coords you might be interested I have already.

**Comment by HexTree** [comment]
Ok for the first step we have decided to just use a WebView, which shows the openstreetmaps site (as long as Wifi is on). This will be so that we have at least a workable prototype which I can show the staff. After that, we can think about replacing it.

**Comment by HexTree** [comment]
249767f63f5b7cf49e4fb08b54ebea98d771e6c8 Made a simple webview so at least we have something which resembles a map for the time being (for the purposes of showing staff). But it's not quite what we aim for. 

![app travel](https://cloud.githubusercontent.com/assets/7933725/8508125/91191124-226c-11e5-9c18-c83d09091421.png)

The guide @Virtakuono gave at https://github.com/mapswithme/api-android explains how to integrate maps.me with a custom-made app. I'll give this a try soon. As for data, I think we may as well include everything you have to offer in the way of markers and coordinates.

**Comment by HexTree** [comment]
New branch "mapsme" made for focusing on maps.me support. Have added the maps.me library in 972c176caead2014ac1ad5e5eb476175c9c4f169. If you click on Travel, it asks automatically asks you to download the maps.me app, and directs you to the appropriate market page.

Only issue is that I can't download the app on my 2.3.4 phone as it claims it is incompatible. I think this is because of a problem with my phone, as the website says they support 2.3 . I'll test with another phone.
