### ISSUE TITLE
About - improve look

### ISSUE THREAD

**Issue by HexTree** [HexTree/orientation-app#50]
Right now it's just basic text. If someone thinks they can improve the look, feel free to do so. Also, we could make the email address a hyper-link, but I don't know how to do that.
![about](https://cloud.githubusercontent.com/assets/7933725/9150407/dec95224-3ddf-11e5-956f-c478eb408e69.png)
Not a high priority task.

**Comment by hadjimy** [comment]
This looks ok, perhaps you can add some white margin and just say acknowledgements and enumerate the people involved. (the less this text the better)

**Comment by Uchman21** [comment]
check out to current form

**Comment by HexTree** [comment]
The font looks fine, but I don't think centred layout should be used for large blocks of text, only for small snippets of text. Left aligned is probably best, though you could make the first paragraph centred.

Maybe the acknowledgements could be bullet-pointed.

Also the text does not appear to be scrollable (if it rolls over the end of the page). We need to change that.

![about back](https://cloud.githubusercontent.com/assets/7933725/9150718/cc13e1be-3df1-11e5-8952-939c4963a8e5.png)

**Comment by HexTree** [comment]
Also we should not mention the name of the university in the first sentence. This is something we discussed with graduate services, we'll avoid all mentions of the university until this can be discussed in more depth with Communications.
