### ISSUE TITLE
Checklist - tell users that checklist items are clickable

### ISSUE THREAD

**Issue by HexTree** [HexTree/orientation-app#55]
At the moment there is no way of knowing that the Checklist entries are clickable. Maybe we can add a subtitle at the top saying this. Or alternatively a Toast message.

**Comment by Uchman21** [comment]
By the menu you mean the main menu? If so, a normal phone user would know they are clickable. But adding a subtitle on the top would look bad i think, not design wise but logic wise. You can add whatever you want in the about option. Adding a little "how to use" section just after the welcome and app description.

**Comment by Uchman21** [comment]
Or add two buttons under after the welcome and app description. first button for the appreciation and second for a FAQ which would then also contain the "for further information, contact ******" at the end.

**Comment by HexTree** [comment]
No, I'm referring specifically to the Checklist.

**Comment by yipcma** [comment]
a simple hyperlink [details...]() would do

**Comment by HexTree** [comment]
Used a toast. Avoids adding to the layout.
