### ISSUE TITLE
About - font is not very readable

### ISSUE THREAD

**Issue by HexTree** [HexTree/orientation-app#56]
The font in About is not so readable, especially on smaller phones. The letters are a bit thin. Maybe we can increase the size or thickness, or try alternate fonts.

**Comment by Uchman21** [comment]
Can make it thicker

**Comment by yipcma** [comment]
perhaps use same font as in menu items

**Comment by HexTree** [comment]
Ok, will use the thicker font for now. Might need to readdress this in future if it's still not so readable.
